### ISSUE TITLE
Cursor stops blinking after some seconds in the editor

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#105]
I use the version 7.6. After some seconds the cursor stops blinking when I'm working on, for example, assembler code.

Is this a feature? Could I disable it? Because for me it makes editing code more diffecult. I often have to press a button on keyboard to "reactivate" it.

**Comment by GeorgRottensteiner** [comment]
Thanks! I never noticed. It's a glorious system wide setting of Windows, so I can't really fix it.
As a workaround I force a recreation of the caret every 5 seconds. Seems to fix it as far as I could see.
Fixed with commit #6a7f943c2ae781ffcc401fb87f55a5dd64678ce0

I've updated the WIP version with the fix (https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip), version should be 7.6.1 now.

**Comment by hkramer70** [comment]
Oh really?! I normally write code on macos only. I use the windows pc only for gaming and C64Studio 👯. I am a beginner with windows settings...sorry.

I tried out your version and it works well so far :D. Thanks for your support.

**Comment by GeorgRottensteiner** [comment]
Just noticed that the workaround throws ObjectDisposedException quite a lot, I've uploaded a fix for the fix :)

**Comment by hkramer70** [comment]
Your last version works well for me since yesterday evening. My reported issue is fixed from my sight of view :). Thx!

**Comment by GeorgRottensteiner** [comment]
Glad to be of service!
