### ISSUE TITLE
Graphical artifacts in the Solution Explorer view when opening sub folders

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#111]
I'm working with the release version 7.8.

I open the studio. A solution (my actual work) with one project is opened automatically. The Project node is collapsed in the view.
I expand the Project node. There are a source file and two subfolders. I expand the two subfolders. Then I get that graphic artefacts in the Solution explorer (see image).

I can work with that. So it has not a high impact on my work. It seems to be a visual bug only.

And, unfortunately, I can't reproduce it. It happens only sometimes and it may not occur if I click in the same way those UI items a second time.
![Screenshot 2024-05-31 174456](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/a0063482-66c3-4992-88b5-41782ac8270a)

**Comment by GeorgRottensteiner** [comment]
Yeah, I'm aware of that. I do too much custom drawing in the native TreeView control, esp. for the GIT overlay icons. The expand/collapse animation messes up the drawing offsets.

That's why I started replacing controls with fully custom drawn counter parts (Label Explorer is one of these, as are all the buttons). 
Will be fixed as soon as I get around to replacing that control in the Solution Explorer as well.

**Comment by GeorgRottensteiner** [comment]
Basically fixed with commit #4f2f5dfcdba53e30a06901d35cd5362cdb6c22d4, control is completely replaced and seems mostly in working order.
