### ISSUE TITLE
Can't use string as comparision value inside !if

### ISSUE THREAD

**Issue by truebluepl** [GeorgRottensteiner/C64Studio#120]
Hello Georg,

Simple example:
```
VARIABLE='abc' ; works ok

;doesn't work
!if(VARIABLE='def'){
}
```

Would be nice if it works:)

**Comment by GeorgRottensteiner** [comment]
In this case it's because apostrophes are interpreted as single character, whereas quotes are used for strings. 
If you use quotes the check works:

`VARIABLE="abc" ; works ok

;doesn't work
!if(VARIABLE="def"){
}`

If using apostrophes VARIABLE is actually set to the first character of the literal. Of course the behaviour is still somewhat wonky, I ought to make it more consistent, or spit out warnings of potential unwanted side effects.

**Comment by truebluepl** [comment]
Ah, all right. I've changed conditions and now is ok:) Thank you!
