### ISSUE TITLE
Assembler Debugging not breaking with VICE 3.3

### ISSUE THREAD

**Issue by tingtron** [GeorgRottensteiner/C64Studio#58]
With default VICE tool parameters (using Setup Wizard):
```
Calling C:\path\VICE33\x64sc.exe with -truedrive +virtualdev -initbreak 0x2000 -remotemonitor 
    "C:\path\C64Studio70\Sample Projects\Sample Project 1\sample1.prg"
```
There is no stop in C64 Studio debugger. It just has the following session:
![Asm_Debug_VICE](https://user-images.githubusercontent.com/2383820/149651832-80366dc3-97d9-49e4-8ab5-72281dc149b5.png)

In fact, it looks like VICE does not even run the program.

However, when manually entering `SYS 8192` in the VICE BASIC session,
debugging behaves as expected (for `-initbreak` and/or explicit breaks),

Expected: the program is executed in VICE automatically and is stopped in C64 Studio,
without having to type `SYS 8192` in BASIC.

It might be an issue with the VICE "autostart" feature, even though in VICE Help,
it is supposed to work with different kinds media (disk, tape, etc) and both BASIC and ML.
Note: using the extra parameter `-autostart` had the same issue.

**Comment by GeorgRottensteiner** [comment]
Does the program have a BASIC stub calling SYS 8192? 

Or is it plain assembly starting at $2000?

In the first case, it ought to work out of the box.
In the latter case, the C64 nor C64Studio automatically jumps at the assembly start address. 
That is like the machine behaves.

It sounds like you'd like C64Studio make the emulator automatically jump at the assembly address as well?

**Comment by tingtron** [comment]
Initially I was expecting the debugger to stop automatically for a plain assembler code (as in "Sample Project 1").

Now I realize and remember from earlier that for C64 there should be a short BASIC stub like `10 SYS 8192`.
Looks like there is an assembler macro to do that: `!basic`.

I am trying to figure out now what the best practices are, such as:
- What load address to chose for `*=$????`? Possibly to match regular BASIC location (`2049/$0801`).
- Change the "Debug Start Address" in Project Properties to this new address+stub offset

**Comment by GeorgRottensteiner** [comment]
The load address has to match the BASIC start address, for C64 it's $0801. Otherwise the emulator/C64 can't start the BASIC program as that is where it expects it to begin.

-initbreak with $a871 is correct for every regular case. This address is inside the BASIC ROM, a few moments before the BASIC program begins to run. C64Studio breaks there and inserts all other breakpoints. 
This is to avoid triggering any data breakpoints before, during the RAM test.

From your last paragraph in the comment I deduce it works now as expected? In that case, I'm closing this.
