### ISSUE TITLE
Debugging does not work with GTKVICE 3.6.1

### ISSUE THREAD

**Issue by ArrSeaJay** [GeorgRottensteiner/C64Studio#69]
It seems like C64 studio and VICE freeze up when I start debugging.
The log:
Debugging main.asm
Calling C:\Tools\GTK3VICE-3.6.1-win64\bin\x64sc.exe with -drive8truedrive +virtualdev8 -initbreak 0xa871 -binarymonitor -binarymonitoraddress 127.0.0.1:6510 -moncommands "C:\Users\Ralf\AppData\Local\Temp\tmpF62D.tmp" "C:\Users\Ralf\Documents\dev\c64\Shooter\shooter.prg"
Connection attempt 1 succeeded

When I close C64 studio VICE starts appropriately and even shows the monitor window.

Is that a bug or did I miss something in the C64 studio config?

**Comment by GeorgRottensteiner** [comment]
Hmm, it's weirdly broken. 
C64Studio is waiting for the debugger to hit the initial breakpoint at $a871, but VICE appears hung.

**Comment by GeorgRottensteiner** [comment]
It's a bug. I found that redirecting stdout for the called emulator causes it to hang. I added that when VICE would bail out with some message regarding malformed parameters which are not visible to the caller otherwise. And back then it worked. I've got to investigate why that doesn't seem to work anymore.

**Comment by GeorgRottensteiner** [comment]
Fixed the bug, but I find that the interface is still flaky (the C64Studio part), I need to check a few things before I can upload a fix.

**Comment by ArrSeaJay** [comment]
That's good news. Thanks for the quick response :-D

**Comment by GeorgRottensteiner** [comment]
Seems to work now. I'm pretty sure there's the one or other issue left. Commit is #3b64165b5c8cd4d0cf2c56fa52cceeb16eea2951

Since I'm still inside a rather big modification, I fear the current code state is not compilable (I'm a lazy git and don't do branches)
I've uploaded a preview version to https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

**Comment by ArrSeaJay** [comment]
Works for me now. Thanks a lot.
