### ISSUE TITLE
Const value not shown in 'Find all references'

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#97]
Example below. Line numbers added for clarity. Once compiled, doing a right click -> Find all references on DEBUGVALUE only shows the reference found on lines 3 and 6 but NOT on line 10. Using version 7.5.

```
01 DEBUG
02 
03 DEBUGVALUE = 10
04
05 !ifdef DEBUG {
06   DEBUGVALUE = 11
07 }
08
09   * = $2000 
10   lda #DEBUGVALUE
11   sta $1fff
```

**Comment by GeorgRottensteiner** [comment]
Whoa, that's a good one. Due to internal handling and you redefining DEBUGVALUE there exist two symbols. This is by design, esp. required for debugging and for e.g. for loops.
The find references code simply picks the first matching symbol it finds. Another minor issue is that the first symbol returned should not really have DEBUGVALUE=11 as reference :)

I'm on holidays so can't promise a quick fix. It shouldn't really take long though.

**Comment by mokdevel** [comment]
Not a show stopper. Go enjoy your holiday!

**Comment by GeorgRottensteiner** [comment]
Got around to look at it right away, should be fixed with commit #c6701a0b3e133925568545c865e98eabf2fd87eb

This of course also affected rename references.

**Comment by mokdevel** [comment]
Great to hear. I'll wait for the WIP to get updated. No rush. Thanks!

**Comment by GeorgRottensteiner** [comment]
WIP is updated with the fix inside, have at it!

**Comment by mokdevel** [comment]
Tested and works! Thanks!
